adapterConfig:
  create: true
  files:
    adapter-config.yaml: examples/kubernetes/adapter-config.yaml
  log:
    level: info

adapterTaskConfig:
  create: true
  files:
    task-config.yaml: examples/kubernetes/adapter-task-config.yaml
    job.yaml: examples/kubernetes/job.yaml

broker:
  create: true
  type: googlepubsub
  googlepubsub:
    projectId: CHANGE_ME
    subscriptionId: CHANGE_ME
    topic: CHANGE_ME
    deadLetterTopic: CHANGE_ME

image:
  registry: CHANGE_ME
  repository: hyperfleet-adapter
  pullPolicy: Always
  tag: latest

rbac:
  resources:
    - namespaces
    - jobs
