apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-config
  namespace: "{{ .clusterId }}-remote"
  labels:
    hyperfleet.io/cluster-id: "{{ .clusterId }}"
  annotations:
    hyperfleet.io/generation: "{{ .generation }}"
data:
  cluster_id: "{{ .clusterId }}"
