adapterConfig:
  create: true
  files:
    adapter-config.yaml: examples/remote/adapter-config.yaml
adapterTaskConfig:
  create: true
  files:
    task-config.yaml: examples/remote/adapter-task-config.yaml
    configmap.yaml: examples/remote/configmap.yaml
broker:
  create: true
  type: googlepubsub
  googlepubsub:
    projectId: CHANGE_ME
    subscriptionId: CHANGE_ME
    topic: CHANGE_ME
    deadLetterTopic: CHANGE_ME
image:
  registry: CHANGE_ME
  repository: hyperfleet-adapter
  pullPolicy: Always
  tag: latest
